 CREATE TABLE `employee` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOM` text NOT NULL,
  `PRENOM` text NOT NULL,
  `NOM_UTILISATEUR` varchar(255) NOT NULL,
  `E_MAIL` varchar(255) NOT NULL,
   `POSTES` text NOT NULL,
  `TELEPHONE` text NOT NULL,
  `MOT_DE_PASSE` varchar(255) NOT NULL,
  `MOT_DE_PASSE_CONF` varchar(255) NOT NULL,
  `USER_TYPE` text NOT NULL DEFAULT 'user_simple',
  `ETAT` text NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NOM_UTILISATEUR` (`NOM_UTILISATEUR`),
  UNIQUE KEY `E_MAIL` (`E_MAIL`),
  UNIQUE KEY `TELEPHONE` (`TELEPHONE`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 |
